version: '2.4'
services:
  bot:
    build: .
    restart: "unless-stopped"
    environment:
      TG_API_KEY:
      URL_PATH:
      URL_HOSTNAME:
      URL_PROXY_HOST:
      MONGO_HOST: "mongo"
      MONGO_USER: "mongo"
      MONGO_PASSWORD: "1234secure"
      MONGO_DB: "rules_rules"
      HEALTHCHECK_URL: "/healthcheck"

      MODULE_NAME: 'main'
      VARIABLE_NAME: 'app'
      APP_MODULE: 'main:app'
      WORKERS_PER_CORE: 1
      WEB_CONCURRENCY: 1
